---
title: "Final Notebook"
author: "Riley Bagwell and Rylea Williams"
date: "5/12/2020"
output: html_document
---

```{r setup, include=FALSE}
library(RSQLite)
newdb <- dbConnect(SQLite(), dbname="Science_Catalog.db")
```

To start this project our original plan was scrapped, and a new plan was developed. To integrate all of the correct information we decided to break down each column of our final table into different tables. This was done so that all of the information could be input and stored according to what each table had specified. To begin our project we decided what type of information we wanted to include in our final table. This included, and is not limited to, a specimen ID, specimen name, kingdom ID, phylum ID, class ID, order ID, family ID, genus ID, species ID, storage location ID, and date aquired. For this time the only type of specimens that our table can handle is animals or specimens that can fullfill the taxonomy requirements.

To begin coding each column was broken down into a new table. The first table generated was the kingdom table. This table contains an ID which is an integer and that integer is the primary key of the table. The table also contains a description which is a text value.

```{sql connection=newdb}
CREATE TABLE Kingdom(
Kingdom_ID INTEGER PRIMARY KEY,
Kingdom_Description TEXT NOT NULL
)
```

The same table was repeatedly generated for the rest of the taxonomy that was used for the final table we created. Each table has an integer primary key as its ID column, and a text value as the description column. Each value in the table must contain information for the table to function properly. The following code was generated for the taxonomy.

```{sql connection=newdb}
CREATE TABLE Phylum(
Phylum_ID INTEGER PRIMARY KEY,
Phylum_Description TEXT NOT NULL
)
```

```{sql connection=newdb}
CREATE TABLE Class(
Class_ID INTEGER PRIMARY KEY,
Class_Description TEXT NOT NULL
)
```

```{sql connection=newdb}
CREATE TABLE Orders(
Order_ID INTEGER PRIMARY KEY,
Order_Description TEXT NOT NULL
)
```

```{sql connection=newdb}
CREATE TABLE Family(
Family_ID INTEGER PRIMARY KEY,
Family_Description TEXT NOT NULL
)
```

```{sql connection=newdb}
CREATE TABLE Genus(
Genus_ID INTEGER PRIMARY KEY,
Genus_Description TEXT NOT NULL
)
```

```{sql connection=newdb}
CREATE TABLE Species(
Species_ID INTEGER PRIMARY KEY,
Species_Description TEXT NOT NULL
)
```

Next a storage location table was created. This was done so that the location of the specimen could be easily input into the final table, and each column would contain specific information for the specimens whereabouts. Much like the previous tables this one also contains an ID that is an integer primary key. It also contains a building ID that references another table for storage purposes that will be discussed next. The building ID is also an integer. The table also contains a room and floor column that is a varchar or varibale character which can contain letters and numbers. 

```{sql connection=newdb}
CREATE TABLE Storage_Location(
Storage_Location_ID INTEGER PRIMARY KEY,
Building_ID INTEGER NOT NULL REFERENCES Building,
Room VARCHAR(20) NOT NULL,
Floor VARCHAR(20) NOT NULL
)
```

Next a building table was created that would contain information that was collected for the previous table. This table contains an ID that is an integer and a building description that is a text value. This table and the previous table tie together so that the storage location tabl can gather the specific building information from the building table.

```{sql connection=newdb}
CREATE TABLE Building(
Building_ID INTEGER PRIMARY KEY,
Building_Description TEXT NOT NULL
)
```

Finally, all of the tables necessary to create the main table of interest for the database. The following table will draw information all of the above tables. Each table is interconnected, and from the demonstration video an ERD was displayed so that the connections could be seen more clearly. It may be helpful to view that image again. Each ID in the table has a reference to their corresponding tables in which information was input into.

```{sql connection=newdb}
CREATE TABLE Specimens(
Specimen_ID VARCHAR(20) PRIMARY KEY,
Specimen_name VARCHAR(20) NOT NULL,
Kingdom_ID INTEGER REFERENCES Kingdom,
Phylum_ID INTEGER REFERENCES Phylum,
Class_ID INTEGER REFERENCES Class,
Order_ID INTEGER REFERENCES Orders,
Family_ID INTEGER REFERENCES Family,
Genus_ID INTEGER REFERENCES Genus,
Species_ID INTEGER REFERENCES Species,
Storage_Location_ID INTEGER REFERENCES Storage_Location,
Date_Aquired DATE
)
```

A select statement was written to make sure that the table did not contain any errors after its generation.

```{sql connection=newdb}
SELECT * FROM Specimens
```

Next infromation was input into the first table created, the kingdom table. To satisfy the columns of the kingdom table the Kingdom table was first selected, and each column was specified in the code. Then values were inserted corresponding with the correct values. For the kingdom_ID an integer was inserted, and for the kingdom_Description a line of text was inserted. We decided to created four different options for four different kingdoms used in taxonomy. The code below shows the four different kingdoms inserted into the table.

```{sql connection=newdb}
INSERT INTO Kingdom (Kingdom_ID, Kingdom_Description)
VALUES(1, "Animals"), (2, "Plants"), (3, "Protists"), (4, "Fungi")
```

A select statement for the kingdom table was written to check for any errors, and to make sure the values were correctly input into the table.

```{sql connection=newdb}
SELECT * FROM Kingdom
```

Very similar inserts were done for the tables after Kingdom for the taxonomy of a specimen. The code was written in choronoligical order. We decided to input four different specimens into each table to show the variety of specimens and their taxonomy. For our examples we chose a tiger, scorpion, octopus, and a roundworm to demonstrate some variety. The following code expresses the input of ID integers, and descriptions into each of the taxonomy tables.

```{sql connection=newdb}
INSERT INTO Phylum (Phylum_ID, Phylum_Description)
VALUES(1, "Chordate"), (2, "Arthropoda"), (3, "Mollusca"), (4, "Nematoda")
```

```{sql connection=newdb}
INSERT INTO Class (Class_ID, Class_Description)
VALUES (1,"Mammalia"), (2, "Arachnida"), (3, "Cephalopoda"), (4, "Chromadorea")
```

```{sql connection=newdb}
INSERT INTO Orders (Order_ID, Order_description)
VALUES(1, "Carnivora"), (2, "Scorpiones"), (3, "Octopoda"), (4, "Ascaridida")
```

```{sql connection=newdb}
INSERT INTO Family (Family_ID, Family_Description)
VALUES(1, "Felidae"), (2, "Chactidae"), (3, "Octopodidae"), (4, "Ascarididae")
```

```{sql connection=newdb}
INSERT INTO Genus (Genus_ID, Genus_Description)
VALUES(1, "Panthera"), (2, "Anuroctonus"), (3, "Octopus"), (4, "Ascaris")
```

```{sql connection=newdb}
INSERT INTO Species (Species_ID, Species_Description)
VALUES(1, "tigris"), (2, "pococki"), (3, "vulgaris"), (4, "lumbricoides")
```

Next an insert into the building table was done. While the majority of the specimens that would be input into this database will be in the Wood Science Building a second building option was added to show that more than one building can be added to the table and can be referenced in the final specimen table. The buildings chosen were, of course, the Wood Science Building as well as the Geiger Center. These values were input by identiying a building_ID and a building_description, in which the building name serves as the description.

```{sql connection=newdb}
INSERT INTO Building (Building_ID, Building_Description)
VALUES(1, "Wood_Science"), (2, "Geiger_Center")
```

Finally, information was input into the storage location table. The data input satisfies all of the columns for the table generated. The location was given an ID number, the building_ID was the same integer from the building_ID of the building table. If we look closely building_ID 1 from the building table indeicates the specimen is in the scienec building, in the storage location table Building_ID 1 also corresponds with the science building because that information is referenced from the building table. To finish the input a room and floor number were assigned.

```{sql connection=newdb}
INSERT INTO Storage_Location(Storage_Location_ID, Building_ID, Room, Floor)
VALUES(3, 1, "117", 2), (2, 1, "118", 1), (1, 1, "201A", 2)
```

A select statement was written to extract all of the information from the storage location table to check for errors, or any wrongly input data.

```{sql connection=newdb}
SELECT * FROM Storage_Location
```

Finally, data was inserted into the specimens table for each of the specimens previously mentioned. To recap, the specimens were a tiger, scorpion, octopus, and a roundworm. For the infromation to be referenced in the specimen table the corresponding ID was used from each of the previous tables that were created. A specimen ID was given in the form of a variable character, a specimen name was given for each specimen, and then the ID numbers for each table were input corresponding to the ID from each table. Finaly, a date was added to show when the specimen was input.

```{sql connection=newdb}
INSERT INTO Specimens (Specimen_ID, Specimen_name, Kingdom_ID, Phylum_ID, Class_ID, Order_ID, Family_ID, Genus_ID, Species_ID, Storage_Location_ID, Date_Aquired)
VALUES("T01", "Tiger", 1, 1, 1, 1, 1, 1, 1, 1, "2019-07-29"), ("S01", "Scorpion", 1, 2, 2, 2, 2, 2, 2, 1, "2019-03-07"), ("O01", "Octopus", 1, 3, 3, 3, 3, 3, 3, 2, "2018-09-18"), ("R01", "Round_Worm", 1, 4, 4, 4, 4, 4, 4, 2, "1998-11-30")
```

A select statement was written to select all of the data from the table. The table gives all of the data in the form of the ID numbers. We did not like the way the data was represented as integers, because the viewer may have a hard time understanding what the information means.

```{sql connection=newdb}
SELECT * FROM Specimens
```

To rectify the issue with out data being represeneted as integers a natual join was performed. Each column was selected that contained an integer ID. The columns were then renamed to the corresponding table name. Once each column was selected from the specimen table it was joined with each table that contained an ID column. A natural join was selected because if the information from the specimens table was identical to the corresponding table that data was being referenced from it would combine the information with ease. To explain this further if the code for kingdom is viewed in the following select statement it is much easier to understand. To start the Kingdom_Description column was selected from the Kingdom table. This was named AS Kingdom. This column was selected from the Specimens table. It was then joined to the Kingdom table ON the column from the spcimens table that has the Kingdom_ID. The Kingdom_ID column from the specimen table contains the same information as the Kindgom_ID from the Kingdom table therefore they are equal. Once the code was completed for each of the tables that had data represented as integers. Once the code block is run it will then be seen as the proper description instead of a number.

```{sql connection=newdb}
SELECT
Specimens.Specimen_ID AS "Specimen ID",
Specimens.Specimen_name AS "Specimen Name", 
Kingdom.Kingdom_Description AS "Kingdom",
Phylum.Phylum_Description AS "Phylum",
Class.Class_Description AS "Class",
Orders.Order_Description AS "Order",
Family.Family_Description AS "Family",
Genus.Genus_Description AS "Genus",
Species.Species_Description AS "Species",
Building.Building_description AS "Building",
Storage_location.Room,
Storage_Location.Floor,
Date_Aquired AS "Date Aquired"
FROM Specimens
JOIN Kingdom ON Specimens.Kingdom_ID=Kingdom.Kingdom_ID
JOIN Phylum ON Specimens.Phylum_ID=Phylum.Phylum_ID
JOIN Class ON Specimens.Class_ID=Class.Class_ID
JOIN Orders ON Specimens.Order_ID=Orders.Order_ID
JOIN Family ON Specimens.Family_ID=Family.Family_ID
JOIN Genus ON Specimens.Genus_ID=Genus.Genus_ID
JOIN Species ON Specimens.Species_ID=Species.Species_ID
JOIN Storage_Location ON Specimens.Storage_Location_ID = Storage_Location.Storage_Location_ID
JOIN Building ON Storage_Location.Building_ID=Building.Building_ID
```




